//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details_of_vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Details_of_vehicles()
        {
            this.Track_to_travel = new HashSet<Track_to_travel>();
        }
    
        public string License_plate { get; set; }
        public int Type { get; set; }
        public int several_places { get; set; }
        public double Quantity_of_fuel_per_km { get; set; }
    
        public virtual Type_of_vehicles Type_of_vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track_to_travel> Track_to_travel { get; set; }
    }
}
