//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details_of_vehicles
    {
        public string License_plate { get; set; }
        public int Type { get; set; }
        public int several_places { get; set; }
        public string Status { get; set; }
        public int User_id { get; set; }
    
        public virtual Type_of_vehicles Type_of_vehicles { get; set; }
        public virtual Users Users { get; set; }
    }
}
