//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hour_of_work_to_driver
    {
        public int Id { get; set; }
        public int Driver_s_code { get; set; }
        public string Day { get; set; }
        public System.TimeSpan Work_from_hour { get; set; }
        public System.TimeSpan Work_to_hour { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
