//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities1 : DbContext
    {
        public DataBaseEntities1()
            : base("name=DataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Details_of_vehicles> Details_of_vehicles { get; set; }
        public virtual DbSet<Hour_of_work_to_driver> Hour_of_work_to_driver { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Passengers_to_track> Passengers_to_track { get; set; }
        public virtual DbSet<Track_to_travel> Track_to_travel { get; set; }
        public virtual DbSet<Travels> Travels { get; set; }
        public virtual DbSet<Type_of_vehicles> Type_of_vehicles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
