//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers_to_track
    {
        public int Id { get; set; }
        public int Passenger_s_code { get; set; }
        public int Track_s_code { get; set; }
    
        public virtual Passengers Passengers { get; set; }
        public virtual Track_to_travel Track_to_travel { get; set; }
    }
}
