//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_to_travel
    {
        public int Track_s_code { get; set; }
        public int Travel_s_code { get; set; }
        public int Driver_s_Id { get; set; }
        public string License_plate { get; set; }
        public System.DateTime Date_of_travel { get; set; }
        public System.TimeSpan Hour_of_begin { get; set; }
    
        public virtual Details_of_vehicles Details_of_vehicles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Travels Travels { get; set; }
    }
}
