//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Travels()
        {
            this.Track_to_travel = new HashSet<Track_to_travel>();
            this.Passengers = new HashSet<Passengers>();
        }
    
        public int Travel_s_code { get; set; }
        public string Collection_or_dispersing { get; set; }
        public string Destination_or_source { get; set; }
        public System.TimeSpan Hour { get; set; }
        public string Frequency { get; set; }
        public System.DateTime Date_of_begin { get; set; }
        public System.DateTime Date_of_end { get; set; }
        public int Group_s_code { get; set; }
        public double lat { get; set; }
        public double lng { get; set; }
    
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track_to_travel> Track_to_travel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passengers> Passengers { get; set; }
    }
}
