//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Details_of_vehicles = new HashSet<Details_of_vehicles>();
            this.Hour_of_work_to_driver = new HashSet<Hour_of_work_to_driver>();
            this.Track_to_travel = new HashSet<Track_to_travel>();
        }
    
        public int User_s_Id { get; set; }
        public string Name_of_user { get; set; }
        public string Address_of_user { get; set; }
        public string Phone_of_user { get; set; }
        public Permition Permition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_of_vehicles> Details_of_vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hour_of_work_to_driver> Hour_of_work_to_driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Track_to_travel> Track_to_travel { get; set; }
    }
}
